### ISSUE TITLE
Using the confetti effect in our product

### ISSUE THREAD

**Issue by maltsev** [CoderZ90/confetti#1]
Nice work with this confetti effect!

Are we allowed to use it in our product?

**Comment by CoderZ90** [comment]
Hello! Maltsev 
The confetti library is not written by me it's a third-party library created by another person I wanted to give credit to him/her but I don't remember where I got the code from. I got it from a forum post and now I forgot from which forum post I got it from 😅 sorry.....
that's why I don't know if you can use this in your project or not ....
